# version: "3.9"


# networks:
#   deploy-guide-dev:
#     driver: bridge
    
services:
  app:
    container_name: deploy-guide
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    # networks:
    #     - deploy-guide-dev
    depends_on:
        - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: conusecool
    ports:
        - "5432:5432"
    # networks:
    #     - deploy-guide-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:    